import type { Metadata } from "next";
import {Rubik} from 'next/font/google'
import "./globals.css";
import Navbar from "./ui/navbar";
import TopArrow from './ui/topArrow';
export const rubik = Rubik({
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className}`}>
        <Navbar/>
        {children}
        {/* <TopArrow/> */}
      </body>
    </html>
  );
}
